package nlp

type Token string

const (
    LEFT_ROUND_BRACKET                    = "("
    RIGHT_ROUND_BRACKET                   = ")"
    COMMA                                 = ","
    COLON                                 = ":"
    PERIOD                                = "."
    CLOSING_QUOTATION_MARK                = "'"
    OPENING_QUOTATION_MARK                = "`"
    NUMBER_SIGN                           = "#"
    CURRENCY                              = "$"
    CONJUNCTION_COORDINATING              = "CC"
    CARDINAL_NUMBER                       = "CD"
    DETERMINER                            = "DT"
    EXISTENTIAL_THERE                     = "EX"
    FOREIGN_WORD                          = "FW"
    CONJUNCTION_SUBORDINATING             = "IN"
    CONJUNCTION_PREPOSITION               = "IN"
    ADJECTIVE                             = "JJ"
    ADJECTIVE_COMPARATIVE                 = "JJR"
    ADJECTIVE_SUPERLATIVE                 = "JJS"
    LIST_ITEM_MARKER                      = "LS"
    VERB_MODAL_AUXILIARY                  = "MD"
    NOUN_SINGULAR                         = "NN"
    NOUN_MASS                             = "NN"
    NOUN_PROPER_SINGULAR                  = "NNP"
    NOUN_PROPER_PLURAL                    = "NNPS"
    NOUN_PLURAL                           = "NNS"
    PREDETERMINER                         = "PDT"
    POSSESSIVE_ENDING                     = "POS"
    PRONOUN_PERSONAL                      = "PRP"
    PRONOUN_POSSESSIVE                    = "PRP$"
    ADVERB                                = "RB"
    ADVERB_COMPARATIVE                    = "RBR"
    ADVERB_SUPERLATIVE                    = "RBS"
    ADVERB_PARTICLE                       = "RP"
    SYMBOL                                = "SYM"
    INFINITIVAL_TO                        = "TO"
    INTERJECTION                          = "UH"
    VERB_BASE_FORM                        = "VB"
    VERB_PAST_TENSE                       = "VBD"
    VERB_GERUND_PARTICIPLE                = "VBG"
    VERB_PRESENT_PARTICIPLE               = "VBG"
    VERB_PAST_PARTICIPLE                  = "VBN"
    VERB_NON_3RD_PERSON_SINGULAR_PRESENT  = "VBP"
    VERB_3RD_PERSON_SINGULAR_PRESENT      = "VBZ"
    WH_DETERMINER                         = "WDT"
    WH_PRONOUN_PERSONAL                   = "WP"
    WH_PRONOUN_POSSESSIVE                 = "WP$"
    WH_ADVERB                             = "WRB"
)
